version: "3.7"
services:
  gympoint-api:
    build:
      context: ./gympoint-api
      dockerfile: _prd.Dockerfile
    env_file: .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "yarn start"
    networks:
      - "webnet"

  postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - "webnet"

  mongo:
    image: mongo:4.2-bionic
    volumes:
      - "./data/mongo:/data/db"
    ports:
      - "27017:27017"
    networks:
      - "webnet"

networks:
  webnet:
    driver: bridge
