version: "3.7"
services:
  meetapp-api:
    build:
      context: ./meetapp
    env_file: .env
    volumes:
      - "./meetapp:/usr/app"
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    networks:
      - "webnet"

  postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - "webnet"

  mongo:
    image: mongo:4.2-bionic
    volumes:
      - "./data/mongo:/data/db"
    ports:
      - "27017:27017"
    networks:
      - "webnet"

networks:
  webnet:
    driver: bridge
